### PR TITLE
feat(*) convert plugin to the PDK and new DB

### PR DESCRIPTION
**Pull request by ghost**
We're switching to the Kong PDK and the new DAO in order to support Kong Community 1.x and Kong Enterprise 0.35+.

PDK changes:
- kong.request.get_body decodes JSON using the array metatable
- kong.response.exit respects enabled_headers
- add kong.table.merge
- replace kong.tools.responses, kong.tools.utils, kong.tools.public, kong.singletons and ngx.log by various utilities of the PDK

DAO changes:
- update schema and tests to reflect the new DAO

### CODE REVIEW

**Review by kidd — APPROVED** [review]
+1

**Review by Tieske — CHANGES_REQUESTED** [review]
looks good but...

When spinning out the plugin from Kong core, the integration tests were lost because there was no way to mock them. The mocks were fixed in the Kong core mocks.

Since then the mocks are new externally available, see https://github.com/Kong/kong/pull/4454

But that also means that we need to bring those back now (and probably extend some).

**Comment by Tieske** [comment]
also: it should be renamed back to lambda again, to replace the old lambda plugin that can then be removed from the Kong and Kong-EE code bases. Please do check whether it needs a migration in that case, since the schema was altered.

**Comment by ghost** [comment]
> Since then the mocks are new externally available, see Kong/kong#4454

Thanks @Tieske! I updated the PR to bring back the fixtures.

> also: it should be renamed back to lambda again, to replace the old lambda plugin that can then be removed from the Kong and Kong-EE code bases. Please do check whether it needs a migration in that case, since the schema was altered.

This is for another PR I think. 🤔 Now that I think about it, if this plugin is just an extension to the `aws-lambda` plugin, with new IAM roles features, why didn't we add these new features to the upstream plugin?

In my opinion, if we want to combine the two plugins into one, I think we should delete this one and add the IAM roles features upstream i.e. replace this plugin with the one that exists in the CE/EE codebases. But I'm not sure, what's the current process to do this kind of integration work? Do we need to synchronize with team core?

Edit: looks like the trend is to separate the plugin from the CE codebase (?):
- https://github.com/Kong/kong-plugin-proxy-cache
- https://github.com/Kong/kong-plugin-prometheus

**Comment by ghost** [comment]
### To-Do (if we keep the `liamp` plugin in this separated repository):

- [x] Add a .travis.yml
- [x] Update README
- [ ] Update this plugin's docs on https://github.com/Kong/docs.konghq.com
- [ ] Do we need a migration?

**Comment by Tieske** [comment]
> why didn't we add these new features to the upstream plugin?

because it was a build for a customer which was on an old version of Kong.

> I think we should delete this one and add the IAM roles features upstream

> Edit: looks like the trend is to separate the plugin from the CE codebase (?):

Exactly. So this plugin should be renamed back to Lambda, stay in its own external repo, and then the upstream changes would be to remove Lambda there, and update the rockspec to include this external one.

**Comment by Tieske** [comment]
So I just pushed a small update to the readme and tagged it as `0.1.0`.

I'd like to suggest to:

1. Update the readme (as part of this PR)
2. add Travis (as part of this PR)
3. merge this PR
4. tag it as `0.2.0`
5. rename the whole shebang to `aws-lambda` (new PR) possibly adding migrations if needed.
6. tag it as `0.3.0`
7. publish it on LuaRocks as `kong-plugin-aws-lambda` (only the `0.3.0` version)
8. PR to Kong to remove embedded version, and add the external version
9. Update the plugin docs

**Comment by Tieske** [comment]
🎉

**Pull request merged**
