### PR TITLE
chore(*) bump version to 3.2.0

### PR DESCRIPTION
**Pull request by p0pr0ck5**

### CODE REVIEW

**Review by Tieske — COMMENTED** [review]
isn't the change backward incompatible? Shouldn't this be 4.0?

also what's up with the CI failures?

**Comment by p0pr0ck5** [comment]
Well, the change is transparent- no change to the API, no user-facing changes. Under-the-hood management of data changes, but that is also transparent to the user/API request and responses.

As for CI, it fails with:

```
++++nginx -V
++++'[' -x /usr/lib/command-not-found ']'
++++/usr/lib/command-not-found -- nginx
The program 'nginx' can be found in the following packages:
 * nginx-core
 * nginx-extras
 * nginx-full
 * nginx-light
 * nginx-naxsi
Ask your administrator to install one of them
```

Same failure with https://github.com/Kong/kong-plugin-aws-lambda/pull/22. Seems wholy unrelated?

**Review by RobSerafini — APPROVED** [review]

**Comment by RobSerafini** [comment]
I cleared the travis caches, and now getting a error on `kong-plugin-aws-lambda/spec/plugins/aws-lambda/02-schema_spec.lua`

`schema.lua:22: attempt to index global 'kong' (a nil value)`

This is on master too.

**Comment by p0pr0ck5** [comment]
_Whups_. That's fun. Fixed in https://github.com/Kong/kong-plugin-aws-lambda/pull/25

**Pull request merged**
